### ISSUE TITLE
AMQ Broker High Availability Using jdbc for Database - Prerequisites

### ISSUE THREAD

**Issue by zdenek-strm** [aboucham/activemq-artemis-tutorials#1]
Prerequisites: Generate certificates using keytool, create a secret for one way TLS: [4.10.2.2. Configuring one-way TLS]

Is this really a prerequisite? In the tutorial there are instructions to create the secret ext-acceptor-ssl-secret for one-way TLS.

**Comment by aboucham** [comment]
We don't need it :-) 
I will remove it

**Comment by aboucham** [comment]
Done
